db:
  image: postgres
  environment:
    POSTGRES_USER: guess
    POSTGRES_PASSWORD: 123123
web:
  image: php:apache
  volumes:
    - "./vhost.conf:/etc/apache2/sites-enabled/000-default.conf"
    - ".:/var/www/html"
  ports: 
    - "80:80"
  links:
    - db
