db:
  image: postgres
  environment:
    POSTGRES_USER: guess
    POSTGRES_PASSWORD: 123123
  ports:
    - "5432:5432"
  volumes:
    - '.:/root/project'
web:
  build: docker
  volumes:
    - "./vhost.conf:/etc/apache2/sites-enabled/000-default.conf"
    - ".:/var/www/html"
  ports: 
    - "80:80"
  links:
    - db
